spring:
  application:
    name: order
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      repositories:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9094