apiVersion: apps/v1
kind: Deployment
metadata:
   name: foodcatalogueapp
   labels:
      app: foodcatalogueapp
spec:
   replicas: 1
   selector:
      matchLabels:
         app: foodcatalogueapp
   template:
      metadata:
         labels:
            app: foodcatalogueapp
      spec:
         containers:
            - name: foodcatalogueapp
              image: 73768582/foodcatalogue-db:working2
              imagePullPolicy: Always
              ports:
                 - containerPort: 9092
              env: # Environment variables supplied to the Pod
                 - name: SPRING_DATASOURCE_USERNAME # name of environment variable
                   valueFrom: # get value of environment variable from kubernetes secrets
                      secretKeyRef:
                         name: secret
                         key: mysql-username
                 - name: SPRING_DATASOURCE_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: secret
                         key: mysql-password
                 - name: SPRING_DATASOURCE_URL
                   valueFrom:
                      configMapKeyRef:
                         name: configmap
                         key: foodcataloguedb_url
---

apiVersion: v1
kind: Service
metadata:
   name: foodcatalogue-service
spec:
   selector:
      app: foodcatalogueapp
   ports:
      - protocol: TCP
        port: 9092
        targetPort: 9092
        
                  
                    
                    
              
            
              

